import type { FaceShapeType } from '@/features/face-analysis/domain/types';
import type { Hairstyle } from './types';

const shapes: FaceShapeType[] = ['oval', 'round', 'square', 'rectangle', 'heart', 'diamond', 'triangle'];

function scores(values: Partial<Record<FaceShapeType, number>>): Record<FaceShapeType, number> {
  return shapes.reduce(
    (acc, shape) => ({ ...acc, [shape]: values[shape] ?? 58 }),
    {} as Record<FaceShapeType, number>
  );
}

function img(slug: string) {
  return `/hairstyles/${slug}.jpg`;
}

export const HAIRSTYLE_CATALOG: Hairstyle[] = [
  {
    id: 'classic-side-part',
    slug: 'classic-side-part',
    name: 'Classic Side Part',
    description: 'Belahan samping rapi dengan volume ringan untuk tampilan profesional.',
    imageUrl: img('classic-side-part'),
    length: 'short',
    maintenanceLevel: 'medium',
    stylingTimeMinutes: 8,
    tags: ['classic', 'business', 'neat'],
    faceShapeScores: scores({ oval: 96, round: 86, square: 88, rectangle: 78, heart: 84 }),
  },
  {
    id: 'textured-crop',
    slug: 'textured-crop',
    name: 'Textured Crop',
    description: 'Crop pendek bertekstur yang menambah struktur tanpa terlihat berat.',
    imageUrl: img('textured-crop'),
    length: 'short',
    maintenanceLevel: 'low',
    stylingTimeMinutes: 5,
    tags: ['textured', 'modern', 'low-maintenance'],
    faceShapeScores: scores({ oval: 92, round: 88, square: 90, rectangle: 74, diamond: 84 }),
  },
  {
    id: 'french-crop',
    slug: 'french-crop',
    name: 'French Crop',
    description: 'Fringe pendek dan sisi bersih untuk proporsi wajah yang lebih seimbang.',
    imageUrl: img('french-crop'),
    length: 'short',
    maintenanceLevel: 'low',
    stylingTimeMinutes: 4,
    tags: ['crop', 'fringe', 'clean'],
    faceShapeScores: scores({ oval: 90, rectangle: 86, heart: 86, diamond: 84, triangle: 78 }),
  },
  {
    id: 'crew-cut',
    slug: 'crew-cut',
    name: 'Crew Cut',
    description: 'Potongan pendek praktis dengan bagian atas sedikit lebih panjang.',
    imageUrl: img('crew-cut'),
    length: 'short',
    maintenanceLevel: 'low',
    stylingTimeMinutes: 3,
    tags: ['short', 'practical', 'clean'],
    faceShapeScores: scores({ oval: 92, square: 90, diamond: 84, triangle: 82, round: 72 }),
  },
  {
    id: 'ivy-league',
    slug: 'ivy-league',
    name: 'Ivy League',
    description: 'Crew cut panjang dengan styling samping yang fleksibel.',
    imageUrl: img('ivy-league'),
    length: 'short',
    maintenanceLevel: 'medium',
    stylingTimeMinutes: 7,
    tags: ['classic', 'smart', 'versatile'],
    faceShapeScores: scores({ oval: 96, square: 88, rectangle: 82, heart: 86, triangle: 82 }),
  },
  {
    id: 'buzz-cut',
    slug: 'buzz-cut',
    name: 'Buzz Cut',
    description: 'Potongan sangat pendek yang menonjolkan garis wajah.',
    imageUrl: img('buzz-cut'),
    length: 'short',
    maintenanceLevel: 'low',
    stylingTimeMinutes: 1,
    tags: ['minimal', 'sharp', 'short'],
    faceShapeScores: scores({ oval: 88, square: 92, diamond: 80, triangle: 78, round: 62 }),
  },
  {
    id: 'high-and-tight',
    slug: 'high-and-tight',
    name: 'High and Tight',
    description: 'Sisi sangat pendek dengan bagian atas ringkas untuk siluet tegas.',
    imageUrl: img('high-and-tight'),
    length: 'short',
    maintenanceLevel: 'low',
    stylingTimeMinutes: 3,
    tags: ['sharp', 'fade', 'masculine'],
    faceShapeScores: scores({ oval: 88, square: 94, diamond: 82, round: 76, triangle: 78 }),
  },
  {
    id: 'low-fade-crop',
    slug: 'low-fade-crop',
    name: 'Low Fade Crop',
    description: 'Crop pendek dengan fade rendah untuk transisi yang halus.',
    imageUrl: img('low-fade-crop'),
    length: 'short',
    maintenanceLevel: 'medium',
    stylingTimeMinutes: 5,
    tags: ['fade', 'crop', 'balanced'],
    faceShapeScores: scores({ oval: 92, round: 88, rectangle: 82, heart: 84, diamond: 84 }),
  },
  {
    id: 'mid-fade-quiff',
    slug: 'mid-fade-quiff',
    name: 'Mid Fade Quiff',
    description: 'Quiff bervolume dengan fade sedang untuk menambah tinggi visual.',
    imageUrl: img('mid-fade-quiff'),
    length: 'medium',
    maintenanceLevel: 'medium',
    stylingTimeMinutes: 10,
    tags: ['volume', 'fade', 'modern'],
    faceShapeScores: scores({ oval: 94, round: 92, square: 86, heart: 80, triangle: 86 }),
  },
  {
    id: 'high-fade-pompadour',
    slug: 'high-fade-pompadour',
    name: 'High Fade Pompadour',
    description: 'Pompadour tinggi dengan sisi fade untuk tampilan kuat dan rapi.',
    imageUrl: img('high-fade-pompadour'),
    length: 'medium',
    maintenanceLevel: 'high',
    stylingTimeMinutes: 15,
    tags: ['volume', 'pompadour', 'statement'],
    faceShapeScores: scores({ oval: 94, round: 90, square: 88, triangle: 86, rectangle: 70 }),
  },
  {
    id: 'modern-pompadour',
    slug: 'modern-pompadour',
    name: 'Modern Pompadour',
    description: 'Versi pompadour lebih natural dengan tekstur lembut.',
    imageUrl: img('modern-pompadour'),
    length: 'medium',
    maintenanceLevel: 'high',
    stylingTimeMinutes: 14,
    tags: ['pompadour', 'modern', 'volume'],
    faceShapeScores: scores({ oval: 95, round: 88, square: 86, heart: 82, triangle: 86 }),
  },
  {
    id: 'short-quiff',
    slug: 'short-quiff',
    name: 'Short Quiff',
    description: 'Quiff pendek yang mudah distyling dan tetap memberi volume depan.',
    imageUrl: img('short-quiff'),
    length: 'short',
    maintenanceLevel: 'medium',
    stylingTimeMinutes: 7,
    tags: ['quiff', 'volume', 'easy'],
    faceShapeScores: scores({ oval: 94, round: 90, square: 88, diamond: 84, triangle: 84 }),
  },
  {
    id: 'messy-quiff',
    slug: 'messy-quiff',
    name: 'Messy Quiff',
    description: 'Quiff tekstur acak yang santai namun tetap punya bentuk.',
    imageUrl: img('messy-quiff'),
    length: 'medium',
    maintenanceLevel: 'medium',
    stylingTimeMinutes: 10,
    tags: ['textured', 'casual', 'volume'],
    faceShapeScores: scores({ oval: 94, round: 88, rectangle: 82, heart: 86, diamond: 88 }),
  },
  {
    id: 'side-swept-fringe',
    slug: 'side-swept-fringe',
    name: 'Side Swept Fringe',
    description: 'Fringe menyamping untuk melembutkan dahi dan garis wajah.',
    imageUrl: img('side-swept-fringe'),
    length: 'medium',
    maintenanceLevel: 'medium',
    stylingTimeMinutes: 9,
    tags: ['fringe', 'soft', 'balanced'],
    faceShapeScores: scores({ oval: 90, rectangle: 88, heart: 92, diamond: 86, square: 80 }),
  },
  {
    id: 'curtain-fringe',
    slug: 'curtain-fringe',
    name: 'Curtain Fringe',
    description: 'Belahan tengah lembut untuk frame wajah natural.',
    imageUrl: img('curtain-fringe'),
    length: 'medium',
    maintenanceLevel: 'medium',
    stylingTimeMinutes: 10,
    tags: ['fringe', 'korean', 'soft'],
    faceShapeScores: scores({ oval: 92, rectangle: 88, heart: 90, diamond: 90, triangle: 76 }),
  },
  {
    id: 'two-block-cut',
    slug: 'two-block-cut',
    name: 'Two Block Cut',
    description: 'Sisi pendek dengan layer atas lebih panjang untuk gaya modern Asia.',
    imageUrl: img('two-block-cut'),
    length: 'medium',
    maintenanceLevel: 'medium',
    stylingTimeMinutes: 9,
    tags: ['korean', 'layered', 'modern'],
    faceShapeScores: scores({ oval: 94, round: 88, rectangle: 86, heart: 90, diamond: 86 }),
  },
  {
    id: 'comma-hair',
    slug: 'comma-hair',
    name: 'Comma Hair',
    description: 'Fringe melengkung halus untuk tampilan clean dan trendi.',
    imageUrl: img('comma-hair'),
    length: 'medium',
    maintenanceLevel: 'medium',
    stylingTimeMinutes: 10,
    tags: ['korean', 'fringe', 'polished'],
    faceShapeScores: scores({ oval: 92, rectangle: 88, heart: 92, diamond: 88, round: 82 }),
  },
  {
    id: 'slick-back',
    slug: 'slick-back',
    name: 'Slick Back',
    description: 'Rambut disisir ke belakang untuk kesan matang dan tegas.',
    imageUrl: img('slick-back'),
    length: 'medium',
    maintenanceLevel: 'high',
    stylingTimeMinutes: 12,
    tags: ['classic', 'formal', 'sleek'],
    faceShapeScores: scores({ oval: 92, square: 88, diamond: 84, triangle: 84, rectangle: 74 }),
  },
  {
    id: 'textured-slick-back',
    slug: 'textured-slick-back',
    name: 'Textured Slick Back',
    description: 'Slick back natural dengan tekstur agar tidak terlalu kaku.',
    imageUrl: img('textured-slick-back'),
    length: 'medium',
    maintenanceLevel: 'medium',
    stylingTimeMinutes: 11,
    tags: ['textured', 'formal', 'natural'],
    faceShapeScores: scores({ oval: 94, square: 88, heart: 82, diamond: 86, triangle: 84 }),
  },
  {
    id: 'undercut',
    slug: 'undercut',
    name: 'Undercut',
    description: 'Kontras sisi pendek dan atas panjang untuk gaya tegas.',
    imageUrl: img('undercut'),
    length: 'medium',
    maintenanceLevel: 'medium',
    stylingTimeMinutes: 8,
    tags: ['contrast', 'modern', 'bold'],
    faceShapeScores: scores({ oval: 90, round: 86, square: 88, triangle: 86, rectangle: 70 }),
  },
  {
    id: 'disconnected-undercut',
    slug: 'disconnected-undercut',
    name: 'Disconnected Undercut',
    description: 'Undercut dengan batas tegas untuk statement yang lebih berani.',
    imageUrl: img('disconnected-undercut'),
    length: 'medium',
    maintenanceLevel: 'high',
    stylingTimeMinutes: 12,
    tags: ['bold', 'contrast', 'statement'],
    faceShapeScores: scores({ oval: 88, square: 88, round: 82, triangle: 86, rectangle: 68 }),
  },
  {
    id: 'taper-fade',
    slug: 'taper-fade',
    name: 'Taper Fade',
    description: 'Fade gradual yang rapi dan cocok untuk banyak konteks.',
    imageUrl: img('taper-fade'),
    length: 'short',
    maintenanceLevel: 'medium',
    stylingTimeMinutes: 5,
    tags: ['fade', 'clean', 'versatile'],
    faceShapeScores: scores({ oval: 96, round: 88, square: 90, rectangle: 84, heart: 86, diamond: 86, triangle: 86 }),
  },
  {
    id: 'low-taper',
    slug: 'low-taper',
    name: 'Low Taper',
    description: 'Taper rendah yang subtle untuk tampilan bersih tanpa terlalu ekstrem.',
    imageUrl: img('low-taper'),
    length: 'short',
    maintenanceLevel: 'low',
    stylingTimeMinutes: 4,
    tags: ['taper', 'subtle', 'clean'],
    faceShapeScores: scores({ oval: 94, round: 86, square: 88, rectangle: 86, heart: 86, diamond: 86 }),
  },
  {
    id: 'mid-taper',
    slug: 'mid-taper',
    name: 'Mid Taper',
    description: 'Taper sedang yang menyeimbangkan kesan rapi dan modern.',
    imageUrl: img('mid-taper'),
    length: 'short',
    maintenanceLevel: 'medium',
    stylingTimeMinutes: 5,
    tags: ['taper', 'balanced', 'modern'],
    faceShapeScores: scores({ oval: 94, round: 88, square: 90, heart: 86, triangle: 86 }),
  },
  {
    id: 'skin-fade',
    slug: 'skin-fade',
    name: 'Skin Fade',
    description: 'Fade sampai kulit untuk hasil bersih dan kontras.',
    imageUrl: img('skin-fade'),
    length: 'short',
    maintenanceLevel: 'high',
    stylingTimeMinutes: 6,
    tags: ['fade', 'sharp', 'fresh'],
    faceShapeScores: scores({ oval: 88, round: 86, square: 92, diamond: 84, triangle: 84 }),
  },
  {
    id: 'drop-fade',
    slug: 'drop-fade',
    name: 'Drop Fade',
    description: 'Fade melengkung mengikuti belakang kepala untuk siluet dinamis.',
    imageUrl: img('drop-fade'),
    length: 'short',
    maintenanceLevel: 'medium',
    stylingTimeMinutes: 6,
    tags: ['fade', 'dynamic', 'modern'],
    faceShapeScores: scores({ oval: 92, round: 88, square: 88, diamond: 88, triangle: 84 }),
  },
  {
    id: 'burst-fade',
    slug: 'burst-fade',
    name: 'Burst Fade',
    description: 'Fade melingkar di area telinga yang cocok untuk gaya bertekstur.',
    imageUrl: img('burst-fade'),
    length: 'medium',
    maintenanceLevel: 'medium',
    stylingTimeMinutes: 8,
    tags: ['fade', 'curly', 'bold'],
    faceShapeScores: scores({ oval: 90, round: 86, square: 88, diamond: 90, triangle: 86 }),
  },
  {
    id: 'faux-hawk',
    slug: 'faux-hawk',
    name: 'Faux Hawk',
    description: 'Volume tengah tanpa ekstrem mohawk penuh.',
    imageUrl: img('faux-hawk'),
    length: 'medium',
    maintenanceLevel: 'medium',
    stylingTimeMinutes: 10,
    tags: ['edgy', 'volume', 'modern'],
    faceShapeScores: scores({ oval: 88, round: 90, square: 86, triangle: 86, rectangle: 68 }),
  },
  {
    id: 'modern-mullet',
    slug: 'modern-mullet',
    name: 'Modern Mullet',
    description: 'Mullet modern dengan tekstur dan proporsi lebih halus.',
    imageUrl: img('modern-mullet'),
    length: 'medium',
    maintenanceLevel: 'medium',
    stylingTimeMinutes: 11,
    tags: ['trendy', 'textured', 'statement'],
    faceShapeScores: scores({ oval: 86, square: 84, diamond: 90, heart: 84, triangle: 88 }),
  },
  {
    id: 'wolf-cut',
    slug: 'wolf-cut',
    name: 'Wolf Cut',
    description: 'Layer shaggy dengan volume atas dan tekstur panjang.',
    imageUrl: img('wolf-cut'),
    length: 'long',
    maintenanceLevel: 'medium',
    stylingTimeMinutes: 12,
    tags: ['layered', 'shaggy', 'trendy'],
    faceShapeScores: scores({ oval: 88, rectangle: 86, heart: 90, diamond: 92, square: 78 }),
  },
  {
    id: 'shaggy-layers',
    slug: 'shaggy-layers',
    name: 'Shaggy Layers',
    description: 'Layer acak yang melembutkan garis wajah dan memberi gerak.',
    imageUrl: img('shaggy-layers'),
    length: 'long',
    maintenanceLevel: 'medium',
    stylingTimeMinutes: 12,
    tags: ['layered', 'soft', 'texture'],
    faceShapeScores: scores({ oval: 90, rectangle: 88, heart: 88, diamond: 92, square: 82 }),
  },
  {
    id: 'medium-layered',
    slug: 'medium-layered',
    name: 'Medium Layered',
    description: 'Layer medium yang fleksibel untuk tampilan natural.',
    imageUrl: img('medium-layered'),
    length: 'medium',
    maintenanceLevel: 'medium',
    stylingTimeMinutes: 10,
    tags: ['layered', 'natural', 'versatile'],
    faceShapeScores: scores({ oval: 96, rectangle: 88, heart: 88, diamond: 90, triangle: 84 }),
  },
  {
    id: 'bro-flow',
    slug: 'bro-flow',
    name: 'Bro Flow',
    description: 'Rambut medium disisir natural ke belakang dengan flow lembut.',
    imageUrl: img('bro-flow'),
    length: 'medium',
    maintenanceLevel: 'medium',
    stylingTimeMinutes: 9,
    tags: ['natural', 'flow', 'medium'],
    faceShapeScores: scores({ oval: 94, rectangle: 86, heart: 86, diamond: 90, square: 82 }),
  },
  {
    id: 'surfer-hair',
    slug: 'surfer-hair',
    name: 'Surfer Hair',
    description: 'Layer medium panjang dengan tekstur santai.',
    imageUrl: img('surfer-hair'),
    length: 'long',
    maintenanceLevel: 'medium',
    stylingTimeMinutes: 10,
    tags: ['casual', 'wavy', 'natural'],
    faceShapeScores: scores({ oval: 90, rectangle: 86, heart: 88, diamond: 90, square: 78 }),
  },
  {
    id: 'man-bun',
    slug: 'man-bun',
    name: 'Man Bun',
    description: 'Rambut panjang diikat untuk gaya praktis dan clean.',
    imageUrl: img('man-bun'),
    length: 'long',
    maintenanceLevel: 'medium',
    stylingTimeMinutes: 8,
    tags: ['long', 'tied', 'practical'],
    faceShapeScores: scores({ oval: 88, square: 86, diamond: 84, triangle: 82, round: 68 }),
  },
  {
    id: 'top-knot',
    slug: 'top-knot',
    name: 'Top Knot',
    description: 'Ikat atas dengan sisi lebih ringkas untuk tampilan tegas.',
    imageUrl: img('top-knot'),
    length: 'long',
    maintenanceLevel: 'high',
    stylingTimeMinutes: 9,
    tags: ['long', 'undercut', 'bold'],
    faceShapeScores: scores({ oval: 86, square: 86, triangle: 86, diamond: 82, round: 70 }),
  },
  {
    id: 'curly-top-fade',
    slug: 'curly-top-fade',
    name: 'Curly Top Fade',
    description: 'Menonjolkan ikal di atas dengan sisi fade bersih.',
    imageUrl: img('curly-top-fade'),
    length: 'medium',
    maintenanceLevel: 'medium',
    stylingTimeMinutes: 9,
    tags: ['curly', 'fade', 'volume'],
    faceShapeScores: scores({ oval: 92, round: 90, square: 88, heart: 86, triangle: 88 }),
  },
  {
    id: 'curly-fringe',
    slug: 'curly-fringe',
    name: 'Curly Fringe',
    description: 'Fringe ikal yang melembutkan dahi dan menambah tekstur.',
    imageUrl: img('curly-fringe'),
    length: 'medium',
    maintenanceLevel: 'medium',
    stylingTimeMinutes: 10,
    tags: ['curly', 'fringe', 'soft'],
    faceShapeScores: scores({ oval: 90, rectangle: 90, heart: 92, diamond: 90, round: 82 }),
  },
  {
    id: 'wavy-side-part',
    slug: 'wavy-side-part',
    name: 'Wavy Side Part',
    description: 'Belahan samping dengan gelombang natural.',
    imageUrl: img('wavy-side-part'),
    length: 'medium',
    maintenanceLevel: 'medium',
    stylingTimeMinutes: 9,
    tags: ['wavy', 'classic', 'natural'],
    faceShapeScores: scores({ oval: 96, rectangle: 86, heart: 86, diamond: 88, square: 86 }),
  },
  {
    id: 'afro-taper',
    slug: 'afro-taper',
    name: 'Afro Taper',
    description: 'Volume natural dengan taper bersih di tepi.',
    imageUrl: img('afro-taper'),
    length: 'medium',
    maintenanceLevel: 'medium',
    stylingTimeMinutes: 8,
    tags: ['curly', 'natural', 'taper'],
    faceShapeScores: scores({ oval: 92, round: 86, square: 90, diamond: 88, triangle: 86 }),
  },
  {
    id: 'caesar-cut',
    slug: 'caesar-cut',
    name: 'Caesar Cut',
    description: 'Fringe pendek rata yang memberi struktur ringkas.',
    imageUrl: img('caesar-cut'),
    length: 'short',
    maintenanceLevel: 'low',
    stylingTimeMinutes: 4,
    tags: ['short', 'fringe', 'classic'],
    faceShapeScores: scores({ oval: 88, rectangle: 90, heart: 86, square: 84, round: 78 }),
  },
  {
    id: 'edgar-cut',
    slug: 'edgar-cut',
    name: 'Edgar Cut',
    description: 'Fringe garis tegas dengan sisi fade untuk look modern.',
    imageUrl: img('edgar-cut'),
    length: 'short',
    maintenanceLevel: 'medium',
    stylingTimeMinutes: 6,
    tags: ['sharp', 'fringe', 'modern'],
    faceShapeScores: scores({ oval: 84, square: 88, diamond: 86, rectangle: 82, round: 76 }),
  },
  {
    id: 'hard-part-fade',
    slug: 'hard-part-fade',
    name: 'Hard Part Fade',
    description: 'Belahan razor tegas dengan fade untuk hasil presisi.',
    imageUrl: img('hard-part-fade'),
    length: 'short',
    maintenanceLevel: 'high',
    stylingTimeMinutes: 8,
    tags: ['sharp', 'fade', 'classic'],
    faceShapeScores: scores({ oval: 92, round: 88, square: 90, triangle: 84, rectangle: 78 }),
  },
  {
    id: 'comb-over-fade',
    slug: 'comb-over-fade',
    name: 'Comb Over Fade',
    description: 'Comb over modern dengan fade untuk tampilan rapi.',
    imageUrl: img('comb-over-fade'),
    length: 'short',
    maintenanceLevel: 'medium',
    stylingTimeMinutes: 8,
    tags: ['classic', 'fade', 'neat'],
    faceShapeScores: scores({ oval: 96, round: 88, square: 88, rectangle: 82, heart: 84 }),
  },
  {
    id: 'brush-up',
    slug: 'brush-up',
    name: 'Brush Up',
    description: 'Rambut atas disisir naik untuk volume ringan.',
    imageUrl: img('brush-up'),
    length: 'medium',
    maintenanceLevel: 'medium',
    stylingTimeMinutes: 9,
    tags: ['volume', 'modern', 'casual'],
    faceShapeScores: scores({ oval: 92, round: 92, square: 86, triangle: 86, rectangle: 72 }),
  },
  {
    id: 'spiky-texture',
    slug: 'spiky-texture',
    name: 'Spiky Texture',
    description: 'Tekstur spike pendek yang memberi arah dan tinggi.',
    imageUrl: img('spiky-texture'),
    length: 'short',
    maintenanceLevel: 'medium',
    stylingTimeMinutes: 7,
    tags: ['texture', 'volume', 'youthful'],
    faceShapeScores: scores({ oval: 88, round: 90, square: 88, triangle: 84, rectangle: 70 }),
  },
  {
    id: 'short-afro',
    slug: 'short-afro',
    name: 'Short Afro',
    description: 'Afro pendek natural dengan bentuk yang terkontrol.',
    imageUrl: img('short-afro'),
    length: 'short',
    maintenanceLevel: 'medium',
    stylingTimeMinutes: 7,
    tags: ['curly', 'natural', 'short'],
    faceShapeScores: scores({ oval: 90, square: 88, round: 84, diamond: 86, triangle: 86 }),
  },
  {
    id: 'temple-fade',
    slug: 'temple-fade',
    name: 'Temple Fade',
    description: 'Fade di area pelipis untuk hasil bersih namun tetap natural.',
    imageUrl: img('temple-fade'),
    length: 'short',
    maintenanceLevel: 'medium',
    stylingTimeMinutes: 5,
    tags: ['fade', 'clean', 'subtle'],
    faceShapeScores: scores({ oval: 92, round: 86, square: 88, heart: 86, diamond: 88 }),
  },
  {
    id: 'bowl-cut-modern',
    slug: 'bowl-cut-modern',
    name: 'Modern Bowl Cut',
    description: 'Bowl cut modern dengan tekstur dan sisi ringan.',
    imageUrl: img('bowl-cut-modern'),
    length: 'medium',
    maintenanceLevel: 'medium',
    stylingTimeMinutes: 8,
    tags: ['fringe', 'modern', 'soft'],
    faceShapeScores: scores({ oval: 84, rectangle: 88, heart: 88, diamond: 86, round: 76 }),
  },
  {
    id: 'long-layered',
    slug: 'long-layered',
    name: 'Long Layered',
    description: 'Rambut panjang berlayer untuk gerak dan frame wajah.',
    imageUrl: img('long-layered'),
    length: 'long',
    maintenanceLevel: 'medium',
    stylingTimeMinutes: 12,
    tags: ['long', 'layered', 'soft'],
    faceShapeScores: scores({ oval: 92, rectangle: 88, heart: 88, diamond: 90, square: 80 }),
  },
  {
    id: 'side-part-taper',
    slug: 'side-part-taper',
    name: 'Side Part Taper',
    description: 'Side part klasik dengan taper halus untuk rutinitas harian.',
    imageUrl: img('side-part-taper'),
    length: 'short',
    maintenanceLevel: 'low',
    stylingTimeMinutes: 6,
    tags: ['classic', 'taper', 'daily'],
    faceShapeScores: scores({ oval: 96, round: 88, square: 90, rectangle: 84, heart: 86, triangle: 84 }),
  },
  {
    id: 'clean-scissor-cut',
    slug: 'clean-scissor-cut',
    name: 'Clean Scissor Cut',
    description: 'Potongan gunting natural yang rapi tanpa fade ekstrem.',
    imageUrl: img('clean-scissor-cut'),
    length: 'medium',
    maintenanceLevel: 'low',
    stylingTimeMinutes: 6,
    tags: ['natural', 'classic', 'versatile'],
    faceShapeScores: scores({ oval: 98, round: 86, square: 88, rectangle: 88, heart: 88, diamond: 88, triangle: 86 }),
  },
];
